# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
